/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kpovodxjyyxaubvwhgdh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwb3ZvZHhqeXl4YXVidndoZ2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMDk5MDgsImV4cCI6MjA4MDc4NTkwOH0.VrvY1lrht-U0E9Za3I9r1Vwe715-fxjdkklk7kMMCB0"